#Arithmetic Operators
a=34
b=4
c=a+b
print(c)
#Asssignment Operators
a=4-2
print(a)
b=6
b -= 3 #decrement the value of b by 3 then it assign ti=o b
print(b)
#Comparison operators
d=5==5
print(d)
#Logical Operators
e=True or False
# Truth table of' OR'
print("True or False is",True or False)
print("True or True is",True or True)
print("False or True is",False or True)
print("False or False is",False or False)

# Truth table of 'AND'
print("True and False is",True and False)
print("True and True is",True and True)
print("False and True is",False and True)
print("False and False is",False and False)

print(not(True))